spring:
  application:
    name: sub_tech_challenge_seller_api_fase4
  data:
    mongodb:
      uri: mongodb+srv://posfiap:posfiap@posfiap.hz8ggjd.mongodb.net/posfiap
      database: vehicle

vehicle:
  url: "http://localhost:8080/api/vehicle"
